---
-  hosts: myservers
   become: yes
   tasks:
   - name: install java on ubuntu 
     apt: 
       name: "{{javaubuntu}}"
       state: present

   - name: install java on redhat
     apt: 
       name: "{{javaredhat}}"
       state: present     