---
-  hosts: myservers
   become: yes
   tasks:
   - name: install java on ubuntu 
     apt: 
       name: "{{javaubuntu}}"
       state: present
     when:  ansible_os_family == "Debian"


   - name: install java on redhat
     dnf: 
       name: "{{javaredhat}}"
       state: present     
     when:  ansible_os_family == "RedHat"