---
- hosts: myservers
  become: yes
  tasks: 
   - name: install webserver on ubuntu node
     apt: 
      name: "{{nodeserver}}"
      state: present
     when:  ansible_os_family == "Debian"

   - name: i want to start a webserver on ubuntu node
     service: 
      name: "{{nodeserver}}"
      state: started 
     when:  ansible_os_family == "Debian"
      
   - name: install webserver on redHat node
     dnf: 
      name: "{{redhatserver}}"
      state: present
     when:  ansible_os_family == "RedHat"

   - name: i want to start webserver on redHat node
     service:
      name: "{{redhatserver}}"
      state: started 
     when:  ansible_os_family == "RedHat"       
       