---
- hosts: 172.31.4.177
  become: yes
  tasks: 
  - name: i want to install direct linux on node
    command: hostname -f
    register : myresult

  - name: i want to display result
    debug: 
        msg: "{{myresult}}"


          
            :   