---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on  ubuntu  nodes
    apt:
      name:  apache2
      state: present
  
  - name: i want to start webserver on ubuntu nodes
    service:
      name: apache2
      state: started
   
  - name: i want to install webserver on redhat nodes
    dnf:
      name: httpd
      state: present
    
  - name: i want to start webserver on redhat nodes
    service:
        name: httpd
        state: started
    