---
- name: download tomcat
  get_url: 
    url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
    dest: /home/ubuntu/tomcatpackage
  force_basic_auth: yes  

- name: create a folder
  file:
   name: /opt/tomcat 
   state: directory

- name: extract
  command: 
      cmd:  sudo tar xzvf /home/ubuntu/apache-tomcat-10.0.20.tar.gz -C /opt/tomcat --strip-components=1
      creates: /opt/tomcat/LICENSE
         